#!/bin/bash
#PBS -l nodes=6:ppn=12
#PBS -l walltime=00:01:00
#PBS -q batch
#PBS -N run_pbs
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
cd ~/FinalProject3

mpiexec -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./dynamic.x
