#!/bin/bash
#PBS -l nodes=1:ppn=12,walltime=00:02:00
#PBS -q batch
#PBS -N run_test
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
cd ~/final/
export COUNTER1=P_WALL_CLOCK_TIME
#mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE -x COUNTER1 ./quicksortN.x
./quicksortN.x
